// Generates a NEW throwaway wallet for GenLayer Studionet and stores it in .env.
// The private key is NEVER printed. Only the address is shown.
import { writeFileSync, existsSync } from "node:fs";
import { createAccount, generatePrivateKey } from "genlayer-js";

if (existsSync(new URL("../.env", import.meta.url)) && !process.argv.includes("--force")) {
  console.error(".env already exists. Pass --force to overwrite (the old key is lost)."
  );
  process.exit(1);
}

const privateKey = generatePrivateKey();
const account = createAccount(privateKey);
const contents = [
  "# Generated by scripts/create-wallet.mjs - NEVER commit this file",
  `PRIVATE_KEY=${privateKey}`,
  `WALLET_ADDRESS=${account.address}`,
  "GENLAYER_RPC_URL=https://studio.genlayer.com/api",
  "",
].join("\n");
writeFileSync(new URL("../.env", import.meta.url), contents, { mode: 0o600 });
console.log(`New wallet address: ${account.address}`);
console.log("Saved to .env (gitignored). The private key was not printed.");
